[package]
name = "weird_iterator"
version = "0.1.0"
authors = ["Adenylatcyclase <streicher1993@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.3.1"